title: Vladislav Andreev - Blog
baseurl: ""
url: "https://vld.by"
social:
  github: vladyio
  twitter: vladyio

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-code-tabs

sass:
  style: compressed

languages:
  en: 🇬🇧
  ru: 🇷🇺
